[project]
name    = "htop"
version = "0.1.0"
entry   = "htop.hop"
target  = "linux/x86_64"

[dependencies]
io     = "linux"
fs     = "linux"
mem    = "linux"
sys    = "linux"
string = "ds"
array  = "ds"
